################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_ssd_st.c \
/Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_st_yolox.c \
/Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_yolov2.c \
/Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_yolov5.c \
/Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_yolov8.c \
/Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/vision_models_pp.c 

OBJS += \
./lib_vision_models_pp/od_pp_ssd_st.o \
./lib_vision_models_pp/od_pp_st_yolox.o \
./lib_vision_models_pp/od_pp_yolov2.o \
./lib_vision_models_pp/od_pp_yolov5.o \
./lib_vision_models_pp/od_pp_yolov8.o \
./lib_vision_models_pp/vision_models_pp.o 

C_DEPS += \
./lib_vision_models_pp/od_pp_ssd_st.d \
./lib_vision_models_pp/od_pp_st_yolox.d \
./lib_vision_models_pp/od_pp_yolov2.d \
./lib_vision_models_pp/od_pp_yolov5.d \
./lib_vision_models_pp/od_pp_yolov8.d \
./lib_vision_models_pp/vision_models_pp.d 


# Each subdirectory must supply rules for building sources it contributes
lib_vision_models_pp/od_pp_ssd_st.o: /Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_ssd_st.c lib_vision_models_pp/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I~/parking-ai/object_detection/STM32N6/Middlewares/AI_Runtime/Npu/ll_aton/ -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
lib_vision_models_pp/od_pp_st_yolox.o: /Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_st_yolox.c lib_vision_models_pp/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I~/parking-ai/object_detection/STM32N6/Middlewares/AI_Runtime/Npu/ll_aton/ -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
lib_vision_models_pp/od_pp_yolov2.o: /Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_yolov2.c lib_vision_models_pp/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I~/parking-ai/object_detection/STM32N6/Middlewares/AI_Runtime/Npu/ll_aton/ -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
lib_vision_models_pp/od_pp_yolov5.o: /Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_yolov5.c lib_vision_models_pp/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I~/parking-ai/object_detection/STM32N6/Middlewares/AI_Runtime/Npu/ll_aton/ -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
lib_vision_models_pp/od_pp_yolov8.o: /Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_yolov8.c lib_vision_models_pp/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I~/parking-ai/object_detection/STM32N6/Middlewares/AI_Runtime/Npu/ll_aton/ -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
lib_vision_models_pp/vision_models_pp.o: /Ubuntu-22.04/home/katkat/parking-ai/object_detection/STM32N6/Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src/vision_models_pp.c lib_vision_models_pp/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I~/parking-ai/object_detection/STM32N6/Middlewares/AI_Runtime/Npu/ll_aton/ -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-lib_vision_models_pp

clean-lib_vision_models_pp:
	-$(RM) ./lib_vision_models_pp/od_pp_ssd_st.cyclo ./lib_vision_models_pp/od_pp_ssd_st.d ./lib_vision_models_pp/od_pp_ssd_st.o ./lib_vision_models_pp/od_pp_ssd_st.su ./lib_vision_models_pp/od_pp_st_yolox.cyclo ./lib_vision_models_pp/od_pp_st_yolox.d ./lib_vision_models_pp/od_pp_st_yolox.o ./lib_vision_models_pp/od_pp_st_yolox.su ./lib_vision_models_pp/od_pp_yolov2.cyclo ./lib_vision_models_pp/od_pp_yolov2.d ./lib_vision_models_pp/od_pp_yolov2.o ./lib_vision_models_pp/od_pp_yolov2.su ./lib_vision_models_pp/od_pp_yolov5.cyclo ./lib_vision_models_pp/od_pp_yolov5.d ./lib_vision_models_pp/od_pp_yolov5.o ./lib_vision_models_pp/od_pp_yolov5.su ./lib_vision_models_pp/od_pp_yolov8.cyclo ./lib_vision_models_pp/od_pp_yolov8.d ./lib_vision_models_pp/od_pp_yolov8.o ./lib_vision_models_pp/od_pp_yolov8.su ./lib_vision_models_pp/vision_models_pp.cyclo ./lib_vision_models_pp/vision_models_pp.d ./lib_vision_models_pp/vision_models_pp.o ./lib_vision_models_pp/vision_models_pp.su

.PHONY: clean-lib_vision_models_pp

