dataset:
  format: coco_format
  class_names: [black-knight,black-pawn,black-queen,black-rook,white-bishop]

coco_format:
  images_path: ../chess_coco/train
  json_annotations_file_path: ../chess_coco/train/_annotations.coco.json
  export_dir: subset_chess/train
  
pascal_voc_format:
  images_path: ../pascal_voc_valid/VOCdevkit/VOC2007/JPEGImages
  xml_files_path: ../pascal_voc_valid/VOCdevkit/VOC2007/Annotations
  export_dir: subset_voc_to_darknet/valid

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}