general:
   model_path: https://github.com/stm32-hotspot/ultralytics/raw/refs/heads/main/examples/YOLOv8-STEdgeAI/stedgeai_models/pose_estimation/yolov8n_256_quant_pt_uf_pose_coco-st.tflite
   model_type: yolo_mpe  # spe, yolo_mpe

operation_mode: prediction

dataset:
   keypoints: 17  # 13

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

postprocessing:
  kpts_conf_thresh: 0.15
  confidence_thresh: 0.001
  NMS_thresh: 0.1
  plot_metrics: false
  max_detection_boxes: 100

prediction:
   test_files_path: ../datasets/COCO_test_dataset_multi_pose

mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
