general:
  project_name: COCO_2017_pose_Demo
  logs_dir: logs
  saved_models_dir: saved_models
  model_path:
  model_type: heatmaps_spe
  num_threads_tflite: 8
  gpu_memory_limit: 8
  global_seed: 123

operation_mode: chain_tqeb
#choices=['evaluation', 'quantization', 'benchmarking',
#         'chain_eqe','chain_qb','chain_eqeb']

dataset:
  name: COCO2017_pose
  keypoints: 17
  training_path: ../datasets/coco_train_single_pose
  # validation_path: ../datasets/coco_val_single_pose
  validation_split: 0.1
  test_path: ../datasets/coco_val_single_pose
  # quantization_path: ../datasets/coco_train_single_pose
  quantization_split: 0.3

preprocessing:
  rescaling: { scale: 1/127.5, offset: -1 }
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb

data_augmentation:
  random_periodic_resizing:
    image_sizes: [[192,192],[224,224],[256,256]]
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.3
  random_flip:
    mode: horizontal
  random_rotation:
    factor: (-0.1,0.1) # -+0.1 = -+36 degree angle

training:
  model:
    name: st_movenet_lightning_heatmaps
    alpha: 1.0
    input_shape: (192, 192, 3)
    pretrained_weights: imagenet
  resume_training_from: # experiments_outputs/2024_11_06_16_44_31/
  frozen_layers: # (0:154)
  batch_size: 64
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.01
  callbacks:
    ReduceLROnPlateau:
      monitor: val_oks
      mode: max
      factor: 0.25
      min_delta: 0.0001
      patience: 5
    ModelCheckpoint:
      monitor: val_oks
      mode: max
    EarlyStopping:
      monitor: val_oks
      mode: max
      min_delta: 0.0001
      patience: 10

quantization:
  quantizer: TFlite_converter #  TFlite_converter or onnx_quantizer
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
  # optimize: True
  # granularity: per_tensor

tools:
   stedgeai:
      version: 10.0.0
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking: # valid options are STM32MP257F-EV1,STM32MP157F-DK2,STM32MP135F-DK
   board: STM32MP257F-EV1

mlflow:
  uri: ./experiments_outputs/mlruns

hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}