general:
   model_path: ../../../model_zoo/semantic_segmentation/deeplab_v3/ST_pretrainedmodel_public_dataset/coco_2017_pascal_voc_2012/deeplab_v3_mobilenetv2_05_16_512_fft/deeplab_v3_mobilenetv2_05_16_512_fft.h5

operation_mode: evaluation

dataset:
   name: pascal_voc
   test_path: ../datasets/VOC2012_train_val/JPEGImages
   test_masks_path: ../datasets/VOC2012_train_val/SegmentationClassAug
   test_files_path: ../datasets/VOC2012_train_val/ImageSets/Segmentation/val.txt

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}