general:
  project_name: handposture
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: True
  global_seed: 42
  gpu_memory_limit: 24
  deterministic_ops: True

operation_mode: training

dataset:
  name: ST_handposture_dataset
  class_names: [None, Like, Dislike, FlatHand, Fist, Love, BreakTime, CrossHands]
  training_path: ../datasets/ST_VL53L8CX_handposture_dataset
  validation_path:
  validation_split: 0.2
  test_path:

preprocessing:
  Max_distance: 400
  Min_distance: 100
  Background_distance:  120

data_augmentation:
  random_flip:
    mode: horizontal

training:
  model:
    name: CNN2D_ST_HandPosture
    version: v1
    input_shape: (8, 8, 2)
  frozen_layers:
  dropout: 0.2
  batch_size: 32
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.01
  callbacks:
    ReduceLROnPlateau:
      monitor: val_loss
      factor: 0.1
      patience: 20
      min_lr: 1.0e-04
    EarlyStopping:
      monitor: val_accuracy
      restore_best_weights: true
      patience: 40

mlflow:
  uri: ./experiments_outputs/mlruns

hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
